/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Allowance } from "./Allowance";

export { Allowance__factory } from "./factories/Allowance__factory";
